from typing import List, Callable, Tuple, Any

def foo(x: int) -> str: ...
def bar(x: List[int]) -> None: ...
def baz(x: Callable[[int, str], float]) -> Any: ...
def brain_damage_edge_case(a: int, b: str, c: List[Tuple[int, ...]]) -> None: ...
